### ISSUE TITLE
Initializing the agent as a distro version instead of extension

### ISSUE THREAD

**Issue by sakthiraam** [domstolene/da-otel-agent#31]
Hi @turesheim , Good Day! Thanks for this development. We are trying to use it in our environment. We already have a distro version of the otel agent and we wanted to add your development to our distro version instead of adding it as an extension. We followed the below example and added your source code under the custom folder but for some reason the custom source code is not getting initialized. Do you have any pointers for us to check.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro

**Comment by turesheim** [comment]
I @sakthiraam. I might be misunderstanding, but [da-opentelemetry-javaagent.jar](https://github.com/domstolene/da-otel-agent/releases/download/1.3.0/da-opentelemetry-javaagent.jar) is a drop-in replacement for `opentelemetry.javaagent.jar`. If you want to add the features from this agent into another custom agent, I don't know how to proceed.
